---
ingress:
  enabled: true
  hosts:
    - grafana.wendy.do.citopro.com
  annotations:
    kubernetes.io/ingress.class: nginx

persistence:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      url: http://wendy-prometheus-server
      access: proxy
      isDefault: true